### ISSUE TITLE
Some metrics are missing.

### ISSUE THREAD

**Issue by reefland** [dotdc/grafana-dashboards-kubernetes#3]
Beautiful dashboards.  Some of the panels show no data, and I've seen this before (Kubernetes LENS).   In reviewing the JSON query it is referencing attributes or keys that are not included with cAdvisor metrics (that I have).  For examples, your Global dashboard:

![grafana_missing_metrics](https://user-images.githubusercontent.com/16230914/175557832-119fdc24-9793-406c-a32f-5c7bc51a6ec9.png)

When I look at the CPU Utilization by namespace and inspect the JSON query it is based on  `container_cpu_usage_seconds_total`.  When I look in my Prometheus it does not have `image=`, here is a random one that was on the top of the query:
```
container_cpu_usage_seconds_total{cpu="total", endpoint="https-metrics", id="/kubepods/besteffort/pod03202a32-75a1-4a64-8692-1e73fd26eca3", instance="192.168.10.217:10250", job="kubelet", metrics_path="/metrics/cadvisor", namespace="democratic-csi", node="k3s03", pod="democratic-csi-nfs-node-sqxp9", service="kube-prometheus-stack-kubelet"}
```

I'm using K3s based on Kubernetes 1.23 on bare metal with containerd, no docker runtime.  I have no idea if this is from containerd, kublet, cAdivsor issue or just expected as part of life when you don't use docker runtime.  

If you have any suggestions, be much appreciated.

**Comment by reefland** [comment]
If I modify the JSON query to be `pod!="` instead of `image!=""` it renders data, not sure it is equal to what you intended.

![grafana_new_query_metrics](https://user-images.githubusercontent.com/16230914/175562024-5aeba64f-49d8-44a8-8664-9dfbffd9672b.png)

**Comment by reefland** [comment]
Lastly, I update the 4 panel's JSON query to be `pod!=""` and it looks good, but I feel my setup is missing something that would provide the `image` key.

![grafana_updated_query_metrics](https://user-images.githubusercontent.com/16230914/175563434-2735cedd-5167-4824-b3b2-483421bb53dd.png)

**Comment by dotdc** [comment]
Hi @reefland,

I'm using them with kube-prometheus-stack and they work well with the `image` label.
I will try to reproduce on k3s next week to see if data is the same with the `pod` label. 
Will update the issue to let you know.

Thank you for the feedback!

**Comment by reefland** [comment]
I'm using kube-prometheus-stack as well.   k3s comes with containerd, but its a limited version.  I install an external containerd/runc from Ubuntu 20.04.4 LTS:

```
containerd/focal-updates,focal-security,now 1.5.9-0ubuntu1~20.04.4 amd64 [installed]
  daemon to control runC

runc/focal-updates,now 1.1.0-0ubuntu1~20.04.1 amd64 [installed,automatic]
  Open Container Project - runtime
```

To get k3s to use a different containerd, you just add a parameter to point it to the alternate socket.  
```
--container-runtime-endpoint=unix:///run/containerd/containerd.sock'
```
(The built-in containerd overlay filesystem does not support ZFS filesystem snapshotter so I can't even test it.)

**Comment by dotdc** [comment]
Just had a quick look this morning and I think the `image` label is missing to reduce cardinality.
Will need to dig a little bit more, but I think using the `container` label instead of the `image` is the best option here.

@reefland Can you try replacing the `image!=""` with `container!=""`and tell me if it works on your setup?

**Comment by reefland** [comment]
This returns empty set:
```
sum(rate(container_cpu_usage_seconds_total{container!=""}[2m])) by (namespace)
```

This returns data:
```
sum(rate(container_cpu_usage_seconds_total{pod!=""}[2m])) by (namespace)

{namespace="longhorn-system"} | 0.3802682252044597
{namespace="unifi"} | 0.010644037623491361
{namespace="democratic-csi"} | 0.07559476845975506
{namespace="monitoring"} | 0.3340142603623991
{namespace="kube-system"} | 0.024392617969317708
{namespace="cert-manager"} | 0.004427970345607981
{namespace="mosquitto"} | 0.002106486317303942
{namespace="argocd"} | 0.10412260998344586
{namespace="traefik"} | 0.007761231914784795
{namespace="vpa"} | 0.0011662568742333156
{namespace="goldilocks"} | 0.00034527230630960895
```

**Comment by dotdc** [comment]
Can you check if you drop some labels in your prometheus/kube-prometheus-stack configuration/values?
If not, can you share more details on your setup, especially kube-prometheus-stack version.

**Comment by reefland** [comment]
Using Chart `36.2.0` of kube-prometheus-stack.   References `image: 'quay.io/prometheus/prometheus:v2.36.1'`

I've haven't done done relabeling or label drops (not sure how to even do that yet).  That should all be "default" settings.

My Prometheus settings for the Helm `values.yaml` are:

```
      prometheusOperator:
        enabled: true

      # Prometheus values

      prometheus:
        enabled: true
        prometheusSpec:
          storageSpec:
            volumeClaimTemplate:
              spec:
                storageClassName: freenas-iscsi-csi
                accessModes: 
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 50Gi

          retention: 21d
          externalUrl: /prometheus
```

Grafana / Alertmanager settings left out for brevity.  As K3s does not deploy everything as a pod, I have some setup in the `values.yaml` on how to reach them:

```
     kubeApiServer:
        enabled: true

      kubelet:
        enabled: true
        namespace: kube-system
        resource: true

      kubeControllerManager:
        enabled: true
        endpoints:
          - 192.168.10.215
          - 192.168.10.216
          - 192.168.10.217
        service:
          enabled: true
          port: 10257
          targetPort: 10257
        serviceMonitor:
          enabled: true
          https: true
          insecureSkipVerify: true

      coreDns:
        enabled: true

      kubeScheduler:
        enabled: true
        endpoints:
          - 192.168.10.215
          - 192.168.10.216
          - 192.168.10.217
        service:
          enabled: true
          port: 10259
          targetPort: 10259
        serviceMonitor:
          enabled: true
          https: true
          insecureSkipVerify: true

      kubeProxy:
        enabled: true
        endpoints:
          - 192.168.10.215
          - 192.168.10.216
          - 192.168.10.217

      kubeEtcd:
        enabled: true
        endpoints:
          - 192.168.10.215
          - 192.168.10.216
          - 192.168.10.217
        service:
          enabled: true
          port: 2381
          targetPort: 2381

      kubeStateMetrics:
        enabled: true
```
