### ISSUE TITLE
Values not showing in namespace total cluster CPU & RAM usage  

### ISSUE THREAD

**Issue by noor-muradi** [dotdc/grafana-dashboards-kubernetes#62]
### Describe the bug

Values not showing in namespace total cluster CPU & RAM usage  (Kubernetes/Views/Namespaces)

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/24589033/faaea37f-fd31-4b6a-ac14-8a17b04541bf)

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/24589033/0b3aeaa9-e714-4a89-b9c2-7e4c7a3f4dcb)

**Comment by dotdc** [comment]
Hi @noor-muradi,

Can you check if you have any results for `kube_pod_container_resource_requests` and `machine_cpu_cores` in Grafana explore?

Did you check if you have a relabeling configuration that drop one or the other?

If not, could you share more context on your setup, version of k8s and deployments related to this issue...

**Comment by noor-muradi** [comment]
@dotdc 
I have not configured any custom relabel, I have deployed the Prometheus & Grafana cluster using the official helm chart, my K8s version is "1.26.6" . Below is the values.yaml, other dashboards are showing values correctly as below screenshot.

```
### Grafana Section ###

grafana:
  enabled: true
  namespaceOverride: ""
 
  grafana.ini:
    smtp:
      enabled: true
      host: smtp.gmail.com:465
      user: xxx
      password: xxx
      from_address: xxx
      from_name: xxx
    server:
      root_url: https://xxx
    wall: true

  persistence:
    enabled: true
    existingClaim: "grafana-pvc"
    accessModes:
      - ReadWriteOnce

  initChownData:
   enabled: false

  resources:
    requests:
      memory: 256Mi
      cpu: 128m
    limits:
      memory: 1Gi
      cpu: 840m

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'grafana-dashboards-kubernetes'
        orgId: 1
        folder: 'Kubernetes'
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
  dashboards:
    grafana-dashboards-kubernetes:
      k8s-system-api-server:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
        token: ''
      k8s-system-coredns:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
        token: ''
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        token: ''
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        token: ''
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        token: ''
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        token: ''

  #default passowrd
  adminPassword: prom-operator

  #disable default dashboard
  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      isDefaultDatasource: true
      uid: prometheus

defaultRules:
 create: false


#### Prometheus Section ###

prometheus:
  enabled: true

  prometheusSpec:
    image:
      registry: quay.io
      repository: prometheus/prometheus
      tag: v2.45.0
      sha: ""
    ## How long to retain metrics
    retention: "10d"
    ## Maximum size of metrics
    retentionSize: "30GB"
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prom-pvc
        spec:
         #storageClassName: nfs-retain
          accessModes: ["ReadWriteOnce"]
          volumeName: prom-pv
          resources:
            requests:
              storage: 5Gi
          selector:
            matchLabels:
              app: prometheus

    resources:
      requests:
        memory: 512Mi
        cpu: 128m
      limits:
        memory: 2Gi
        cpu: 840m


    additionalScrapeConfigs:

      - job_name: 'pfsense'
        static_configs:
        - targets: ['192.168.1.1:9100']

alertmanager:
  ## Deploy alertmanager
  enabled: false
```

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/24589033/ea4e07d3-bfcf-4188-a1d9-46fc31dd82b7)

![image](https://github.com/dotdc/grafana-dashboards-kubernetes/assets/24589033/e326ace4-fbca-4e57-9a21-3613195573d8)
